#!/bin/bash
export SNAME="tcpbin"

. ~/.asdf/asdf.sh
if [ -f ./.env ]; then
   . ./.env
fi

ulimit -n 120000
export HOST=tcpbin.net
export SECRET_KEY_BASE=`cat SECRET`
export ERL_CRASH_DUMP_BYTES=5000000000
export ERL_EPMD_ADDRESS=127.0.0.1
export MIX_ENV=prod
mix deps.get
mix local.rebar --force
mix assets.deploy
mix phx.digest
export ELIXIR_ERL_OPTIONS="+sbwt none -noinput -noshell -sname ${SNAME} +Mea min"
exec elixir -S mix phx.server
